//project drawdown data in GIGATONS CO^2 average value
//projectDrawDown.food.activePercentage
let projectDrawDown = {
    food: {
        potential: 239.05,
        activePercentage: 0.0,
        title: "FOOD AGRICULTURE LAND",
        description: `
        <h5>Address Waste and Diets</h5>
        By shifting diets and addressing food waste, the global demand for food can significantly drop. Eating lower on the food chain and ensuring what’s grown gets eaten is a powerful combination that lowers farming inputs, land-clearing, and all associated emissions.
        
        <h5>Protect Ecosystems</h5>
        When land and ecosystems are deliberately protected, activities that release carbon from vegetation and soil are stopped before they start. In addition, improving food production on existing farmland may reduce the pressure on other, nearby landscapes, thereby sparing them from clearing.
        
        <h5>Shift Agriculture Practices</h5>
        Better agriculture practices can lower emissions from cropland and pastures, including methane generated by growing rice and raising ruminants, nitrous oxide emitted from manure and overusing fertilizers, and carbon dioxide released by disturbing soils.
        `
    },
    industry: {
        potential: 136.6,
        activePercentage: 0.0,
        title: "INDUSTRY",
        description: `
        <h5>Improve Materials</h5>
        Plastic, metals, and cement are some of the most ubiquitous materials. They’re also prime candidates for improvement and replacement with better alternatives that can meet the same needs, but with lower emissions.
        
        <h5>Use Waste</h5>
        Waste can be reclaimed as a resource—something of value, rather than something to discard—to reduce the use of raw materials and energy, thereby reducing emissions. The most advanced approaches move us toward a circular economy.
        
        <h5>Address Refrigerants</h5>
        The chemicals used in refrigeration are potent greenhouse gases, which often leak during use or disposal. We can better manage and dispose of the fluorinated gases currently used as refrigerants, and, ultimately, replace them with benign alternatives.
        
        <h5>Enhance Efficiency</h5>
        Industrial processes can also reduce emissions through energy-efficiency and using low- and no-carbon energy sources.
        `
    },
    electricity: {
        potential: 320.4,
        activePercentage: 0.0,
        title: "ELECTRICITY",
        description: `
        <h5>Enhance Efficiency</h5>
        Electricity efficiency solutions include technologies and practices that reduce demand for electricity generation, literally lightening the load. The two biggest end-users of electricity are buildings and industry, in roughly equal measure. While a home or factory may be the location of efficiency measures, these emissions get counted at the power plant where they are created or avoided, as part of the electricity sector. (See further exploration of buildings and industry below.)
        
        <h5>Shift Production</h5>
        Production of electricity must move away from fossil fuels, as quickly as possible. A spectrum of solutions can help, from small-scale/distributed to large-scale/centralized. Some solutions harvest photons from the sun. Others tap nature’s generous kinetic energy—the movement of wind and water. Still others use an alternate source of heat, such as geothermal or nuclear, for the same basic steam-turbine process.
        
        <h5>Improve the System</h5>
        To enable the transition to renewable electricity production and use, the broader electricity system also needs to evolve and upgrade. Flexible grids for transmission and effective energy storage make it possible to better balance electricity supply with demand.
        `
    },
    landSinks: {
        potential: 315.45,
        activePercentage: 0.0,
        title: "LAND SINKS",
        description: `
        <h5>Address Waste and Diets</h5>
        Reducing food waste and shifting to plant-rich diets are two critical interventions to prevent deforestation. Lower demand for food and farmland spares nature from additional clearing, indirectly protecting carbon sinks.
        
        <h5>Protect and Restore Ecosystems</h5>
        “Let nature be nature” is a powerful principle—let peatlands, grasslands, and forests continue to do what they do best by protecting them from human disturbance. Where ecosystems have been degraded, restoration can help them recuperate form and function, including absorbing and storing more carbon over time.
        
        <h5>Shift Agriculture Practices</h5>
        What and how we grow, graze, or harvest can be a means to cultivate biomass and regenerate soil carbon. An array of “regenerative agriculture” methods are being rediscovered and developed worldwide, and show promising results. The integration of trees into farming through agroforestry practices is particularly powerful. All solutions that sustainably raise yields on existing farmland can also reduce the pressure to clear other areas.
        
        <h5>Use Degraded Land</h5>
        Lastly, degraded lands can be put to use in ways that revive productivity, increase biomass, and promote soil carbon sequestration—all while producing wood, fiber, or food.
        `
    },
    buildings: {
        potential: 107.45,
        activePercentage: 0.0,
        title: "BUILDINGS",
        description: `
        <h5>Enhance Efficiency</h5>
        Whether for building retrofits or brand new construction, energy-efficiency solutions are largely the same. Many address the building “envelope” and insulation—means of keeping conditioned air in and unconditioned air out—while others use technology to optimize energy use.
        
        <h5>Shift Energy Sources</h5>
        Clean alternatives can replace more polluting fossil energy sources typically used to heat space, warm water, or prepare meals.
        
        <h5>Address Refrigerants</h5>
        The gases used as refrigerants today are potent greenhouse gases. We can reduce emissions by managing leaks that often happen within buildings, as well as properly disposing of refrigerants (a waste process that falls under industry, above). Ultimately, these fluorinated gases can be replaced with alternatives that are not greenhouse gases.
        `
    },
    transportation: {
        potential: 77.7,
        activePercentage: 0.0,
        title: "TRANSPORTATION",
        description: `
        <h5>Shift to Alternatives</h5>
        Alternative modes of mobility reduce demand for fossil-fueled transportation or replace it altogether. With public and “pooled” transit, we can make the most of available seats. Compact cities, intentional infrastructure, and advanced communication technologies make it possible to walk, cycle, or simply stay put.
        
        <h5>Enhance Efficiency</h5>
        Where combustion engines remain in use, vehicles can be made far more fuel-efficient through mechanical improvements, lightweighting, better design, and more artful operation.
        
        <h5>Electrify Vehicles</h5>
        Electrification of vehicles completely replaces petroleum—and has even greater benefits when paired with renewable electricity generation.
        `
    }
}

function getActivePercentageOfActiveSector() {
    return projectDrawDown[activeSector].activePercentage;
}

function getActiveSectorProjectDescription() {
    return projectDrawDown[activeSector].description;
}

function getActiveSectorProjectTitle() {
    return projectDrawDown[activeSector].title;
}

let activeSector = 'electricity';
let cummulativePercentage = 0.0;

//clock wise count up / counter clock count down
function setAmountOfActiveSector(oldRotation, newRotation) {
    if (abs(oldRotation-newRotation) > 2) {
        if ((newRotation < oldRotation || oldRotation < 100 && newRotation > 250) && getActivePercentageOfActiveSector() < 100) {
            projectDrawDown[activeSector].activePercentage = getActivePercentageOfActiveSector() + 1;
            updateCummulativePercentage();
        } else if (oldRotation !== newRotation && getActivePercentageOfActiveSector() > 0) {
            projectDrawDown[activeSector].activePercentage = getActivePercentageOfActiveSector() - 1;
            updateCummulativePercentage();

        }
        updatePercentage();
    }
}

function updatePercentage() {
    let e = document.getElementById("foodPercentageDisplay");
    e.innerText = projectDrawDown.food.activePercentage + " %";

    e = document.getElementById("industryPercentageDisplay");
    e.innerText = projectDrawDown.industry.activePercentage + " %";

    e = document.getElementById("electricityPercentageDisplay");
    e.innerText = projectDrawDown.electricity.activePercentage + " %";

    e = document.getElementById("landSinksPercentageDisplay");
    e.innerText = projectDrawDown.landSinks.activePercentage + " %";

    e = document.getElementById("buildingsPercentageDisplay");
    e.innerText = projectDrawDown.buildings.activePercentage + " %";

    e = document.getElementById("transportationPercentageDisplay");
    e.innerText = projectDrawDown.transportation.activePercentage + " %";
}

function resetProjectDrawdown(){
    Object.keys(projectDrawDown).forEach(key => {
        projectDrawDown[key].activePercentage=0;
    });
    updatePercentage();
    updateCummulativePercentage();
}

function setAllProjectDrawdown() {
    Object.keys(projectDrawDown).forEach(key => {
        projectDrawDown[key].activePercentage= 100;
    });
    updatePercentage();
    updateCummulativePercentage();
}

/**
 *  updates the cummulative activePercentage value of each sector taking the total potential into account
 */
function updateCummulativePercentage() {
    let totalPotential = 0;
    let activePotential = 0;
    Object.keys(projectDrawDown).forEach(key => {
        totalPotential += projectDrawDown[key].potential;
        activePotential += projectDrawDown[key].potential * projectDrawDown[key].activePercentage / 100;
    });

    cummulativePercentage = activePotential / totalPotential * 100;

    console.log(`cummulativePercentage: ${cummulativePercentage}`);
}
